config/routes.rb
Rails.application.routes.draw do
  
  authenticated :user do
    root :to => 'requests#index', :as => :authenticated_root
  end
  root :to => redirect('/users/sign_in')
  
  devise_for :users

  resources :attachments, only: [:destroy]

	resources :requests do
    resources :attachments, only: [:new, :create]
  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :request
  has_attached_file :file, :styles => { :original => "250x250>" }, :url => :s3_eu_url
  validates_attachment_file_name :file, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/, /doc\Z/, /pdf\Z/]
  before_post_process :allow_only_images
  
  def allow_only_images
    if !(file.content_type =~ %r{^(image|(x-)?application)/(x-png|pjpeg|jpeg|jpg|png|gif)$})
      return false 
    end
  end 
    
    
end

app/models/request.rb
class Request < ActiveRecord::Base
  
  URGENCY = []
  
  validates_presence_of :title, :details, :requestor_id
  belongs_to :requestor, class_name: "User"
  belongs_to :assignee, class_name: "User", foreign_key: "assigned_to"
  has_many :attachments, dependent: :destroy
  default_scope { order(:urgency => :asc, :created_at => :asc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :requests, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  
  before_action :authenticate_user!
  
  def new
    @request = Request.find(params[:request_id])
    @attachment = @request.attachments.build
  end
  
  def create
    @request = Request.find(params[:request_id])
    logger.debug @request.inspect
    logger.debug attachment_params.inspect
    @attachment = @request.attachments.build(attachment_params)
    if @attachment.save
      flash[:notice] = "Attachment added successfully."
    else
      flash[:error] = "Error uploading attachment."
    end 
    redirect_to @request
  end
  
  def destroy
    @attachment = Attachment.find(params[:id])
    @request = @attachment.request
    @attachment.destroy
    redirect_to @request
  end
  
  private
      # Using a private method to encapsulate the permissible parameters is
      # just a good pattern since you'll be able to reuse the same permit
      # list between create and update. Also, you can specialize this method
      # with per-user checking of permissible attributes.
      def attachment_params
        params.require(:attachment).permit(:file, :request_id)
      end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  before_action :authenticate_user!
  
  
  def index
    if params[:show_complete]
      @requests = Request.all
    else
      @requests = Request.where(:complete => false)
    end
  end
  
  def show
    @request = Request.find(params[:id])
    @attachment = @request.attachments.build
  end
  
  def new   
  end
  
  def update
      @request = Request.find(params[:id])
      previously_complete = @request.complete
      if @request.update_attributes(request_params)
        flash[:notice] = "Request updated successfully."
        # send a completion email
        if ! previously_complete && @request.complete
          BeaconMailer.completion_email(current_user.email, @request).deliver
        end
      end
      redirect_to(:back)
  end
  
  def create
    puts request_params.merge(:requestor_id => current_user.id)
    @request = Request.new(request_params.merge(:requestor_id => current_user.id))
        if @request.save
          BeaconMailer.request_created_email(current_user.email, @request).deliver
          redirect_to :requests
        else
          flash.now[:error] = "Could not save request"
          render :new
        end
  end
  
  private
      # Using a private method to encapsulate the permissible parameters is
      # just a good pattern since you'll be able to reuse the same permit
      # list between create and update. Also, you can specialize this method
      # with per-user checking of permissible attributes.
      def request_params
        params.require(:request).permit(:title, :details, :urgency, :relevancy, :assigned_to, :complete)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def content_type_to_string(content_type)
    mappings = {
      'application/msword' => 'word',
      'application/excel'  => 'excel',
      'text/plain'         => 'text',
      'application/rtf'    => 'text',
      'application/pdf'    => 'pdf'
    }
    mappings[content_type]
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/attachments/new.html.erb
<%= bootstrap_form_for([@request, @attachment], :html => {:class => "col-xs-6"}) do |f| %>
	<%= f.file_field :file %>
	<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
	<span class="glyphicon glyphicon-thumbs-up"></span> Upload
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Beacon</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container-fluid">
			<h1>
				Beacon
			</h1>

			<% if signed_in? %>
			<nav class="navbar navbar-default" role="navigation">
				<ul class="nav navbar-nav">
					<li><%= button_to 'New Request', new_request_path , :class => "btn btn-success navbar-btn", :method => 'get' %></li>
					<li><%= link_to 'All Requests', requests_path %></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li><%= link_to raw("<span class=\"glyphicon glyphicon-log-out\"></span> Logout"), destroy_user_session_path, :method => :delete %> </li>
					<% end %>
				</ul>
			</nav>
			<% end %>
			
			<% if notice %>
				<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
				<p class="alert alert-danger"><%= alert %></p>
			<% end %>
			<%= yield %>

		</div>
	</body>
</html>

app/views/requests/index.html.erb
<div class="table-responsive">
	<table class="table table-bordered">
		<tr>
			<th>Title</th>
			<th>Status</th>
			<th>Urgency</th>
			<th>Requested date</th>
			<th>Requested by</th>
			<th>Handled by</th>
			<th></th>


	<% @requests.each do |request| %>

		<%
			class_name=""
			row_class=""
			if request.complete
				row_class = "active"
				class_name = "active"
			elsif request.assignee
				class_name = "success"
			else 
				class_name = "warning"
			end
		%>
		
		<%
			urgency_class_name=""
			if request.urgency == 1 
				urgency_class_name = "danger"
			elsif request.urgency == 2
				class_name = "warning"
			end
		%>
	
		<tr class=" <%= row_class %>">
			<td><%= link_to request.title, request_path(request) %></td>
			<td><%= request.complete ? "Closed" : "Open" %></td>
			<td class="<%= urgency_class_name %>"><%= request.urgency %></td>
			<td><%= request.created_at.strftime('%-d %B %Y') %></td>
			<td><%= request.requestor.email  %></td>
			<td class="<%= class_name %>"><%= request.assignee ? request.assignee.email : "Not assigned" %></td>
			<% if request.assignee && request.assignee == current_user %>
			<td><%= link_to 'Unassign', request_path(request, :request => { :assigned_to => nil } ), :method => :put %></td>
			<% else %>
			<td><%= link_to 'Assign to me', request_path(request, :request => { :assigned_to => current_user.id } ), :method => :put %></td>
			<% end %>
		</tr>
	<% end %>
	</table>
</div>
<div class="btn-group" role="group" aria-label="...">
	<% if params[:show_complete] %>
	<%= link_to raw("<span class=\"glyphicon glyphicon-remove-circle\"></span> Hide completed"), requests_path, :class => "btn btn-primary" %>
	<% else %>
	<%= link_to raw("<span class=\"glyphicon glyphicon-search\"></span> Show completed"), requests_path(:show_complete => true), :class => "btn btn-primary" %>
	<% end %>
</div>

app/views/requests/new.html.erb
<%= bootstrap_form_for(Request.new, :html => {:class => "col-xs-6"}) do |f| %>
	<%= f.text_field :title %>
	<%= f.text_area :details, :rows => 10 %>
	<%= f.select :urgency, [
		["Today", 1],
		["Tomorrow", 2],
		["This week", 3],
		["Next week", 4],
		["This month", 5],
		["Someday", 6]
	], {:selected => 3} %>
	<%= f.select :relevance_period, [
		["1 week", 1],
		["2 weeks", 2],
		["3 weeks", 3],
		["More", 4]
	], {:selected => 4} %>

	<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
	<span class="glyphicon glyphicon-thumbs-up"></span> Submit
	<% end %>
<% end %>

app/views/requests/show.html.erb
<div class="row">
	<div class="col-md-7">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title"><%= @request.title %></h3>
		  </div>
		  <div class="panel-body">
		    <%= @request.details %>
		  </div>
		</div>
		<div class="btn-group" role="group">
			<% if current_user == @request.assignee %>
			<%= link_to raw("<span class=\"glyphicon glyphicon-ok\"></span> Mark Completed"), request_path(@request, :request => { :complete => true }), :class => "btn btn-primary", :method => :put %> 
			<% end %>
			<% if current_user == @request.requestor %>
			<%= link_to raw("<span class=\"glyphicon glyphicon-upload\"></span> Add Attachment"), new_request_attachment_path(@request), :class => "btn btn-primary" %>
			<% end %>
			<%= link_to raw("<span class=\"glyphicon glyphicon-arrow-left\"></span> Back to Index"), requests_path, :class => "btn btn-default" %>
		</div>
	</div>
	
	<div class="col-md-5">

		<div class="panel panel-default">
		  	<div class="panel-heading">
				<h3 class="panel-title">Attachments</h3>
		  	</div>
			<table class="table">
				<tr>
					<th>File</th>
					<th></th>
				</tr>
				<% for attachment in @request.attachments %>
				<% if ! attachment.new_record? %>
				<tr>
					<td><%= link_to attachment.file.original_filename, attachment.file.url %></td>
					
					<td><%= link_to "Remove", attachment, method: :delete %></td>
				</tr>
				<% end %>
			<% end %>
			</table>
		</div>
		<div class="row">
			
			<%= bootstrap_form_for([@request, @attachment], :html => {:class => "col-xs-6"}) do |f| %>
				<%= f.file_field :file, :label => "Add File" %>
				<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
					<span class="glyphicon glyphicon-thumbs-up"></span> Upload
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<div class="row col-md-8">
	
</div>